### ISSUE TITLE
Alternativ til "grep" command i Windows

### ISSUE THREAD

**Issue by MMAndersen** [neticdk/k8s-workshop#4]
**$ kubectl config view | grep kind-kind**

virker ikke på Windows (11), men kan erstattes med 

**$ kubectl config view | Findstr kind-kind**

**Comment by AllanHoejgaardJensen** [comment]
Thank you for the input, I have added til text in https://github.com/neticdk/k8s-workshop/commit/e9e1b514fea79d255f4fc0ec240be6dc8f19d427 and other feedback from yesterday in:
https://github.com/neticdk/k8s-workshop/commit/0ef7164bcea199269e9cd87c9564c84ba0e45808
